### PR TITLE
Optimize content import from extensions

### PR DESCRIPTION
**Pull request by dylanmccall**
This changes the Kolibri wrapper code to use importcontent instead of
scanforcontent when possible, providing a significant performance
improvement when starting Kolibri for the first time with content
extensions installed.

### CODE REVIEW

**Comment by dylanmccall** [comment]
This turned into a pretty large set of changes, but hopefully the verbosity could be useful as we tune this a bit more in the future. (As for this being way too much Python for here _again_, I'm definitely on board with moving this over to kolibri-installer-gnome after it's landed). Note that at the moment importcontent from a clean slate is failing with an error in Kolibri:

    OSError: [Errno 30] Read-only file system: '/app/share/kolibri-content/Khan_en_Resources/content/databases/1ceff53605e55bef987d88e0908658c5.sqlite3.transfer'
    Traceback (most recent call last):
      File "/app/bin/kolibri", line 11, in <module>
        load_entry_point('kolibri-flatpak-utils==0.0.0', 'console_scripts', 'kolibri')()
      File "/app/lib/python3.7/site-packages/kolibri_flatpak/kolibri_wrapper.py", line 151, in main
        return application.run()
      File "/app/lib/python3.7/site-packages/kolibri_flatpak/kolibri_wrapper.py", line 120, in run
        for operation in self.__iter_content_operations()
      File "/app/lib/python3.7/site-packages/kolibri_flatpak/kolibri_wrapper.py", line 120, in <genexpr>
        for operation in self.__iter_content_operations()
      File "/app/lib/python3.7/site-packages/kolibri_flatpak/kolibri_wrapper.py", line 79, in apply
        return run_kolibri_fn("manage", "importchannel", "disk", self.__channel_id, KOLIBRI_HOME)
      File "/app/lib/python3.7/site-packages/kolibri_flatpak/kolibri_wrapper.py", line 144, in __run_kolibri
        result = subprocess.run([KOLIBRI, *args], env=self.__kolibri_env, check=True)
      File "/usr/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/app/libexec/kolibri', 'manage', 'importchannel', 'disk', '1ceff53605e55bef987d88e0908658c5', '/home/dylan/.var/app/org.learningequality.Kolibri/data/kolibri']' returned non-zero exit status 1.

We're getting there, anyway :)

**Comment by jamalex** [comment]
>providing a significant performance improvement

And, importantly, only marking the intended nodes as visible, even if other nodes (e.g. in curated topics) might now technically have the necessary files to be marked as available as well (unlike with scanforcontent, which would blindly show those ones as well).

**Comment by jamalex** [comment]
>I'm definitely on board with moving this over to kolibri-installer-gnome

Ah, hmm, except that this is predominantly specific to Flatpak/Flatpak-extensions, not necessarily generalizable to broader GNOME contexts -- or?

**Comment by dylanmccall** [comment]
> And, importantly, only marking the intended nodes as visible, even if other nodes (e.g. in curated topics) might now technically have the necessary files to be marked as available as well

Ah, yes, I was meaning to note that but wasn't sure how to phrase it. Thank you! I pushed an updated commit message :)

> Ah, hmm, except that this is predominantly specific to Flatpak/Flatpak-extensions, not necessarily generalizable to broader GNOME contexts -- or?

The Flathub folks usually encourage putting Flatpak-specific code with the rest of the application where possible; to treat it like any other platform-specific code. It makes things easier with stuff like continuous integration, and for the usual preoccupation of keeping packages simple, but it also is nice to have at least the complicated Python code rooted one place. I figure the flatpak extension code is _mostly_ generic, anyway, or at least could be if it needed to be in the future. And, mostly, adding this feature made me very grumpy about the hierarchy of wrapper scripts I somehow accumulated. (`kolibri-gnome` does stuff to Kolibri and then runs the Python code, which then runs `/app/bin/kolibri`, which is actually the content extension prerun stuff, which then runs `/app/libexec/kolibri`, which is getting terribly evil). So anything to cut back on that is probably a win for maintainability.

**Comment by dylanmccall** [comment]
I changed this to use `scanforcontent --database-only` as proposed in learningequality/kolibri#7275. That works well here with the proposed change :)

**Comment by dylanmccall** [comment]
This will be replaced by learningequality/kolibri-installer-gnome#6, which moves this code to kolibri-installer-gnome itself.

**Pull request closed without merging**
